name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Build application image
        run: docker build -t faculdade-fastapi-app .

      - name: Simulate deployment
        run: echo "Deploy realizado com sucesso"
